<?php

/**
 * @file
 * Contains book_publisher.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function book_publisher_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the book_publisher module.
    case 'help.page.book_publisher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage publisher for book catalogue') . '</p>';
      return $output;

    default:
  }
}
